# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(db_index=True, max_length=255)),
                ('item_title', models.CharField(db_index=True, max_length=255)),
                ('motion', models.TextField(db_index=True)),
                ('action_requested', models.CharField(db_index=True, max_length=255)),
                ('date', models.CharField(db_index=True, max_length=255)),
                ('committee', models.CharField(db_index=True, max_length=255)),
                ('proposed_by', models.CharField(db_index=True, max_length=255)),
                ('presenter', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(db_index=True)),
                ('participation', models.TextField(db_index=True)),
                ('approval_route', models.TextField(db_index=True)),
                ('final_approver', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(db_index=True, max_length=255)),
                ('date', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(db_index=True, default='', max_length=255, unique=True)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('time', models.CharField(db_index=True, max_length=255)),
                ('attendees', models.CharField(db_index=True, max_length=255)),
                ('url', models.CharField(db_index=True, max_length=255)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='main_search.Items')),
            ],
        ),
    ]
