# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-23 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_in_pdf', models.CharField(db_index=True, default='', max_length=255)),
                ('separate_index', models.CharField(db_index=True, default='', max_length=255)),
                ('title', models.CharField(db_index=True, default='', max_length=255)),
                ('pages_start', models.CharField(db_index=True, default='', max_length=255)),
                ('pages_end', models.CharField(db_index=True, default='', max_length=255)),
                ('text', models.CharField(db_index=True, default='', max_length=255)),
                ('keywords', models.CharField(max_length=255, null=True)),
                ('discussion', models.TextField(db_index=True, max_length=255)),
                ('purpose', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion', models.CharField(db_index=True, default='', max_length=255)),
                ('carried', models.CharField(db_index=True, default='', max_length=255)),
                ('content', models.CharField(db_index=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Presenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('Items', models.ManyToManyField(to='main_search.Items')),
            ],
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='description',
            new_name='attendees',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='filename',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='committee',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='items',
            name='motions',
            field=models.ManyToManyField(to='main_search.Motions'),
        ),
        migrations.AddField(
            model_name='items',
            name='presenters',
            field=models.ManyToManyField(to='main_search.Presenters'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='subsection',
            field=models.ManyToManyField(to='main_search.Subsection'),
        ),
    ]
