# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-24 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_search', '0002_auto_20180323_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
